Repository OasisLMF/OasisLMF, pull requests merged in 2022-11, with the labels that each got.

#1140 [gulpy] bugfix: use the correct itemsize when creating `int32_mv`
  oasislmf/pytools/gul/common.py
  oasislmf/pytools/gul/manager.py
Labels: bug

#1119 use correct condpriority to fix cond class exclusion
  oasislmf/preparation/il_inputs.py
Labels: bug, LTS - 1.26

#1149 Add `--copy-model-data` optional flag to `oasislmf model run`
  oasislmf/computation/generate/losses.py
  oasislmf/execution/bin.py
Labels: enhancement, Feature

#1167 Add support for codecov.io
  .github/workflows/unittest.yml
  codecov.yml
  setup.cfg
Labels: enhancement

#1170 [ci] fix coverage run to produce coverage.xml
  .github/workflows/unittest.yml
  tox.ini
Labels: enhancement
