Repository OasisLMF/OasisLMF, pull requests merged in 2022-06, with the labels that each got.

#1045 bugfix: coverages array should be zeros
  oasislmf/pytools/gul/manager.py
Labels: bug

#1043 Add documentation re the introduction of gulpy
  oasislmf/pytools/gulpy.py
  oasislmf/pytools/introducing_gulpy.md
Labels: Documentation

#1050 Infer the correct mime-type when uploading files to the oasis-platform
  oasislmf/platform/client.py
Labels: bug

#1062 add unsupported peril in the keys-errors file
  oasislmf/lookup/builtin.py
Labels: LTS - 1.23, LTS - 1.26
