Repository OasisLMF/OasisLMF, pull requests merged in 2022-10, with the labels that each got.

#1069 Implement correlated random number generation
  .github/workflows/oasislmf-unittest.yml
  README.md
  oasislmf/computation/generate/files.py
  oasislmf/computation/run/exposure.py
  oasislmf/preparation/correlations.py
  oasislmf/preparation/gul_inputs.py
  oasislmf/pytools/data_layer/oasis_files/correlations.py
  oasislmf/pytools/gul/io.py
  oasislmf/pytools/gul/manager.py
  oasislmf/pytools/gul/random.py
  oasislmf/pytools/gulpy.py
  oasislmf/utils/data.py
  tests/fm/test_fm.py
  tests/fm/test_fmpy.py
  tests/model_preparation/test_summaries.py
  tests/preparation/test_correlations.py
  tests/utils/test_data.py
Labels: enhancement, Feature

#1121 Add support for GUL alloc rule 3
  oasislmf/utils/defaults.py
Labels: bug, LTS - 1.23, LTS - 1.26

#1128 Add CONTRIBUTING guidelines
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: enhancement, Documentation

#1136 Fix: gulpy dynamic buff size
  oasislmf/pytools/gul/manager.py
Labels: bug, enhancement
