Repository OasisLMF/OasisLMF, pull requests merged in 2022-09, with the labels that each got.

#1107 Fix/678 logger
  oasislmf/__init__.py
  oasislmf/cli/command.py
  oasislmf/computation/base.py
  oasislmf/execution/bash.py
  oasislmf/execution/conf.py
  oasislmf/platform_api/client.py
  oasislmf/platform_api/session.py
  oasislmf/preparation/reinsurance_layer.py
  oasislmf/utils/data.py
  oasislmf/utils/inputs.py
  oasislmf/utils/log.py
  oasislmf/validation/model_data.py
  tests/utils/test_log.py
Labels: bug, LTS - 1.26

#1093 Fix call to write_summary_levels - missing IL options
  oasislmf/computation/generate/files.py
  oasislmf/preparation/summaries.py
Labels: bug, LTS - 1.23, LTS - 1.26

#1110 extent api commands with run-inputs/run-losses options
  oasislmf/cli/api.py
  oasislmf/computation/run/platform.py
  oasislmf/manager.py
Labels: enhancement, LTS - 1.23, LTS - 1.26

#1112 Add output type check to the start of generate losses
  oasislmf/computation/generate/losses.py
Labels: bug, LTS - 1.23, LTS - 1.26

#1113 Bugfix: out of bounds cdf
  oasislmf/pytools/gul/io.py
Labels: bug, LTS - 1.23, LTS - 1.26
