Repository OasisLMF/OasisLMF, pull requests merged in 2023-03, with the labels that each got.

#1234 updated exposure run error message for clarity
  oasislmf/computation/run/exposure.py
Labels: bug, LTS - 1.27

#1236 Switch changelog builder from "build" repo to "OasisPlatform"
  .github/workflows/publish.yml
Labels: build system, LTS - 1.27

#1130 Remove check for IL + RI files from the run model cmd
  oasislmf/computation/run/model.py
  oasislmf/utils/data.py
Labels: bug, LTS - 1.27

#1153 Fix generation of dummy model footprint and vulnerability files in cases where there are no impacted bins
  oasislmf/computation/data/dummy_model/generate.py
  oasislmf/computation/generate/files.py
Labels: bug

#1244 Use console entrypoint to define and install `oasislmf` binary
  bin/oasislmf
  oasislmf/cli/root.py
  setup.py
Labels: enhancement

#1242 add fm level 8
  oasislmf/_data/default_acc_profile.json
  oasislmf/_data/default_fm_agg_profile.json
  oasislmf/preparation/il_inputs.py
  oasislmf/utils/fm.py
  validation/insurance_policy_coverage/expected/fm_policytc.csv
  validation/insurance_policy_coverage/expected/fm_profile.csv
  validation/insurance_policy_coverage/expected/fm_programme.csv
  validation/insurance_policy_coverage/expected_subperils/fm_policytc.csv
  validation/insurance_policy_coverage/expected_subperils/fm_profile.csv
  validation/insurance_policy_coverage/expected_subperils/fm_programme.csv
Labels: bug, LTS - 1.27
