Repository OasisLMF/OasisLMF, pull requests merged in 2023-05, with the labels that each got.

#1255 ods_tool version compatibility
  README.md
Labels: documentation

#1257 Fix summary levels file
  oasislmf/preparation/summaries.py
Labels: bug, LTS - 1.27

#1262 specify dtype for useful summary column reading
  oasislmf/preparation/summaries.py
Labels: bug, LTS - 1.27

#1269 specify all jitted functions as nopython
  oasislmf/lookup/builtin.py
  oasislmf/pytools/fm/stream_sparse.py
  oasislmf/pytools/getmodel/footprint.py
  oasislmf/pytools/getmodel/manager.py
Labels: bug, LTS - 1.23, LTS - 1.26, LTS - 1.27

#1254 Pin pandas package to less than 1.5.3 in backports
  requirements-package.in
Labels: bug, LTS - 1.15, LTS - 1.23, LTS - 1.26

#1260 Use low_memory=False in get_dataframe
  oasislmf/utils/data.py
Labels: bug, LTS - 1.15, LTS - 1.23, LTS - 1.26, LTS - 1.27

#1272 Update numpy pin
  requirements-package.in
Labels: bug, LTS - 1.23, LTS - 1.26, LTS - 1.27

#1277 Fix invalid columns in FM tests
  validation/insurance_step/account.csv
  validation/insurance_step/expected/fm_policytc.csv
  validation/insurance_step/units/fm54/account.csv
  validation/insurance_step/units/fm55/account.csv
  validation/insurance_step/units/fm57/account.csv
  validation/insurance_step/units/fm58/account.csv
  validation/insurance_step/units/fm64/account.csv
Labels: bug, LTS - 1.27

#1278 Fixes for newer versions of pandas and numpy
  oasislmf/preparation/reinsurance_layer.py
  oasislmf/pytools/fm/financial_structure.py
  oasislmf/utils/data.py
Labels: bug, LTS - 1.15, LTS - 1.23

#1265 add combine function to lookup built in
  oasislmf/lookup/builtin.py
Labels: feature

#1280 Drop py3.7 in testing and add py3.11
  .github/workflows/unittest.yml
  README.md
Labels: build system

#1286 Improve code coverage accuracy
  .github/workflows/unittest.yml
  oasislmf/utils/forex.py
  tests/conftest.py
  tests/pytools/gul/test_gulpy.py
  tests/pytools/gulmc/test_gulmc.py
Labels: bug, build system

#1289 Fix/fillna on str
  oasislmf/lookup/builtin.py
  oasislmf/preparation/il_inputs.py
  oasislmf/preparation/oed.py
  oasislmf/utils/data.py
Labels: bug

#1290 Added platform client testing
  oasislmf/platform_api/client.py
  oasislmf/platform_api/session.py
  requirements.in
  tests/platform_api/data/analysis_1_output.tar
  tests/platform_api/data/input_sub-tasks.json
  tests/platform_api/data/losses_sub-tasks.json
  tests/platform_api/test_client.py
  tests/platform_api/test_session.py
Labels: enhancement, build system
