Repository OasisLMF/OasisLMF, pull requests merged in 2023-08, with the labels that each got.

#1351 let BI coverage pass through in step policy
  oasislmf/preparation/il_inputs.py
  validation/insurance_and_step/expected/exposure_summary_levels.json
  validation/insurance_and_step/expected/exposure_summary_report.json
  validation/insurance_and_step/expected/fm_policytc.csv
  validation/insurance_and_step/expected/ils.csv
  validation/insurance_and_step/expected/loc_summary.csv
  validation/insurance_and_step/expected_subperils/exposure_summary_levels.json
  validation/insurance_and_step/expected_subperils/exposure_summary_report.json
  validation/insurance_and_step/expected_subperils/fm_policytc.csv
  validation/insurance_and_step/expected_subperils/ils.csv
  validation/insurance_and_step/expected_subperils/loc_summary.csv
  validation/insurance_step/expected/exposure_summary_levels.json
  validation/insurance_step/expected/exposure_summary_report.json
  validation/insurance_step/expected/fm_policytc.csv
  validation/insurance_step/expected/fm_profile.csv
  validation/insurance_step/expected/ils.csv
  validation/insurance_step/expected/loc_summary.csv
Labels: feature

#1352 Support multiple identifiers for footprint files
  .github/workflows/piwind-test.yml
  oasislmf/computation/generate/losses.py
  oasislmf/execution/bin.py
  oasislmf/pytools/getmodel/common.py
  oasislmf/pytools/getmodel/footprint.py
  tests/model_execution/test_bin.py
Labels: enhancement

#1320 Revamp and automate docs build & deployment
  .github/workflows/build-and-deploy-docs.yml
  .github/workflows/build-docs.yml
  .gitignore
  docs/Makefile
  docs/README.md
  docs/build.sh
  docs/prepare-docs.py
  docs/source/api/api_client/client.rst
  docs/source/api/cmd/base.rst
  docs/source/api/cmd/bin.rst
  docs/source/api/cmd/cleaners.rst
  docs/source/api/cmd/config.rst
  docs/source/api/cmd/model.rst
  docs/source/api/cmd/root.rst
  docs/source/api/cmd/test.rst
  docs/source/api/cmd/version.rst
  docs/source/api/exposures/manager.rst
  docs/source/api/exposures/pipeline.rst
  docs/source/api/keys/lookup.rst
  docs/source/api/model_execution/bin.rst
  docs/source/api/model_execution/conf.rst
  docs/source/api/model_execution/files.rst
  docs/source/api/models/model.rst
  docs/source/api/utils/compress.rst
  docs/source/api/utils/conf.rst
  docs/source/api/utils/coverage.rst
  docs/source/api/utils/csv.rst
  docs/source/api/utils/db.rst
  docs/source/api/utils/diff.rst
  docs/source/api/utils/exceptions.rst
  docs/source/api/utils/http.rst
  docs/source/api/utils/log.rst
  docs/source/api/utils/peril.rst
  docs/source/api/utils/status.rst
  docs/source/api/utils/values.rst
  docs/source/cli.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/modules.rst
  docs/source/sphinx.rst
  oasislmf/computation/generate/losses.py
  requirements.in
Labels: documentation
