Repository OasisLMF/OasisLMF, pull requests merged in 2023-02, with the labels that each got.

#1225 short fix: condpriority for cond class exclusion
  oasislmf/preparation/il_inputs.py
Labels: bug, LTS - 1.26

#1218 Fix missing default collumn for RI
  oasislmf/preparation/oed.py
  oasislmf/preparation/reinsurance_layer.py
  oasislmf/utils/data.py
Labels: bug, LTS - 1.27

#1213 Debug complex model execution (#1091) - Backport
  oasislmf/computation/generate/losses.py
  oasislmf/execution/bash.py
  oasislmf/execution/runner.py
Labels: bug, Scalable Architecture, LTS - 1.26

#1222 add option to have custom oed schema
  oasislmf/computation/generate/files.py
  oasislmf/computation/generate/keys.py
  oasislmf/computation/hooks/pre_analysis.py
  oasislmf/computation/run/exposure.py
  oasislmf/computation/run/model.py
  oasislmf/utils/data.py
Labels: enhancement, LTS - 1.27

#1231 Fix expecteted output with Extra TIV cols from ods-tools
  tests/model_preparation/test_exposure_pre_analysis.py
Labels: bug
