Repository OasisLMF/OasisLMF, pull requests merged in 2023-06, with the labels that each got.

#1305 builtin KeyServer not failing when no keys success in a batch
  oasislmf/lookup/factory.py
Labels: bug, LTS - 1.27

#1310 log wrapper, check log level before running input log
  oasislmf/utils/log.py
  tests/utils/test_log.py
Labels: bug, LTS - 1.15, LTS - 1.23, LTS - 1.26, LTS - 1.27

#1306 lookup: remove extra column after failed combine step
  oasislmf/lookup/builtin.py
Labels: bug

#1318 regenerate ids after ExposurePreAnalysis
  oasislmf/computation/hooks/pre_analysis.py
  tests/model_preparation/test_exposure_pre_analysis.py
Labels: bug

#1319 Feature/1316 pre analysis hook
  oasislmf/computation/hooks/pre_analysis.py
Labels: enhancement
