Repository OasisLMF/OasisLMF, pull requests merged in 2023-07, with the labels that each got.

#1296 Pin ods-tools package for new fillna function
  oasislmf/__init__.py
  requirements-package.in
Labels: build system, dependencies

#1270 Add generate and run to rest client
  oasislmf/platform_api/client.py
Labels: enhancement

#1327 Fix/1219 flaky test failures
  tests/model_preparation/test_lookup.py
  tests/utils/test_data.py
Labels: bug, build system

#1261 Implement stochastic disaggregation for items and fm files
  oasislmf/_data/default_fm_agg_profile.json
  oasislmf/preparation/gul_inputs.py
  oasislmf/preparation/il_inputs.py
  oasislmf/pytools/gulmc/aggregate.py
  oasislmf/utils/data.py
  oasislmf/utils/fm.py
  validation/insurance_account/expected/fm_programme.csv
Labels: feature

#1332 fix correlation issue
  oasislmf/pytools/gul/random.py
  tests/pytools/pla/test_plapy.py
Labels: bug

#1335 Update CI - 1.27
  .github/workflows/piwind-mdk.yml
  .github/workflows/piwind-test.yml
  .github/workflows/publish.yml
  .github/workflows/unittest.yml
  README.md
  jenkins/oasislmf.groovy
  jenkins/performance_check.groovy
Labels: build system

#1338 Update CI - 1.26
  .github/workflows/piwind-mdk.yml
  .github/workflows/piwind-test.yml
  .github/workflows/publish.yml
  .github/workflows/unittest.yml
  README.md
  jenkins/oasislmf.groovy
  jenkins/performance_check.groovy
Labels: build system

#1336 Update CI - 1.15
  .github/workflows/piwind-mdk.yml
  .github/workflows/piwind-test.yml
  .github/workflows/publish.yml
  .github/workflows/unittest.yml
  README.md
  jenkins/oasislmf.groovy
  jenkins/performance_check.groovy
Labels: build system

#1334 Update CI - 1.28
  .github/workflows/piwind-mdk.yml
  .github/workflows/piwind-test.yml
  .github/workflows/publish.yml
  .github/workflows/unittest.yml
  README.md
  jenkins/oasislmf.groovy
  jenkins/performance_check.groovy
  tests/platform_api/test_client.py
Labels: build system

#1337 Update CI - 1.23
  .github/workflows/piwind-mdk.yml
  .github/workflows/piwind-test.yml
  .github/workflows/publish.yml
  .github/workflows/unittest.yml
  README.md
  jenkins/oasislmf.groovy
  jenkins/performance_check.groovy
Labels: build system

#1343 Add PiWind testing for both Plat1 and Plat2
  .github/workflows/piwind-test.yml
Labels: build system

#1342 Redefine key_columns as local variable
  .github/workflows/piwind-test.yml
  oasislmf/lookup/builtin.py
Labels: bug

#1349 Fix removal of handlers to logger + give logfiles unique names
  oasislmf/pytools/pla/manager.py
  oasislmf/pytools/utils.py
  tests/cli/test_inputvalues.py
  tests/computation/test_computation.py
  tests/computation/test_generate_files.py
  tests/computation/test_generate_keys.py
  tests/computation/test_generate_losses.py
  tests/computation/test_platform.py
  tests/computation/test_run_generate_files.py
  tests/computation/test_run_model.py
  tests/model_execution/test_bash.py
  tests/model_execution/test_bin.py
  tests/utils/test_data.py
  tests/utils/test_diff.py
Labels: bug
