Repository OasisLMF/OasisLMF, pull requests merged in 2024-09, with the labels that each got.

#1556 Fix CI build system failures
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/unittest.yml
  optional-package.in
Labels: build system

#1559 Read do_disaggregation from settings files
  oasislmf/computation/generate/files.py
Labels: LTS - 2.3

#1554 drop duplicate il term lines before merging
  oasislmf/preparation/il_inputs.py
Labels: bug, LTS - 1.28, LTS - 2.3

#1546 Combus changes: 20240807
  oasislmf/computation/generate/losses.py
  oasislmf/pytools/common/data.py
  oasislmf/pytools/common/event_stream.py
Labels: LTS - 1.28, LTS - 2.3

#1545 large hazard case performance
  oasislmf/pytools/getmodel/footprint.py
Labels: LTS - 2.3

#1555 disable full_correlation if running gulmc
  oasislmf/execution/bash.py
Labels: bug, LTS - 1.27, LTS - 1.28, LTS - 2.3

#1561 Set Ktools 3.12.4
  setup.py
Labels: LTS - 2.3

#1560 add check for vulnerability id and intensity bin boundary
  oasislmf/pytools/getmodel/manager.py
Labels: LTS - 2.3
