Repository OasisLMF/OasisLMF, pull requests merged in 2024-05, with the labels that each got.

#1493 Fix CI default branches
  .github/workflows/piwind-mdk.yml
  .github/workflows/piwind-test.yml
  .github/workflows/unittest.yml
Labels: bug, build system

#1500 Python 3.12 installation issue
  .github/workflows/unittest.yml
  requirements-package.in
Labels: bug, LTS - 2.3

#1494 Extended field list for correlation groupings for disaggregated risks
  oasislmf/preparation/gul_inputs.py
Labels: bug, LTS - 1.28, LTS - 2.3

#1508 fix pla reader
  oasislmf/pytools/common/event_stream.py
  oasislmf/pytools/pla/streams.py
Labels: bug, LTS - 2.3

#1507 update acc_idx to int if not present
  oasislmf/utils/data.py
Labels: bug, LTS - 2.3

#1510 Fix error handling for failed file loading in 'get_dataframe'
  oasislmf/utils/data.py
Labels: bug, LTS - 2.3

#1509 improve perf of file preparation
  oasislmf/computation/generate/files.py
  oasislmf/computation/generate/losses.py
  oasislmf/preparation/gul_inputs.py
  oasislmf/preparation/il_inputs.py
Labels: enhancement, LTS - 1.27, LTS - 1.28, LTS - 2.3

#1505 support ri_scope filter
  oasislmf/computation/generate/files.py
  oasislmf/preparation/oed.py
  oasislmf/preparation/reinsurance_layer.py
  oasislmf/preparation/summaries.py
  tests/fm/test_fmpy.py
  tests/model_preparation/test_reinsurance.py
  validation/reinsurance3/account.csv
  validation/reinsurance3/expected/RI_1/fm_policytc.csv
  validation/reinsurance3/expected/RI_1/fm_profile.csv
  validation/reinsurance3/expected/RI_1/fm_programme.csv
  validation/reinsurance3/expected/RI_1/fm_xref.csv
  validation/reinsurance3/expected/account.csv
  validation/reinsurance3/expected/correlations.csv
  validation/reinsurance3/expected/coverages.csv
  validation/reinsurance3/expected/exposure_info.json
  validation/reinsurance3/expected/exposure_summary_levels.json
  validation/reinsurance3/expected/exposure_summary_report.json
  validation/reinsurance3/expected/fm_policytc.csv
  validation/reinsurance3/expected/fm_profile.csv
  validation/reinsurance3/expected/fm_programme.csv
  validation/reinsurance3/expected/fm_summary_map.csv
  validation/reinsurance3/expected/fm_xref.csv
  validation/reinsurance3/expected/gul_summary_map.csv
  validation/reinsurance3/expected/guls.csv
  validation/reinsurance3/expected/ils.csv
  validation/reinsurance3/expected/items.csv
  validation/reinsurance3/expected/keys.csv
  validation/reinsurance3/expected/location.csv
  validation/reinsurance3/expected/output/raw_guls.csv
  validation/reinsurance3/expected/output/raw_ils.csv
  validation/reinsurance3/expected/output/ri1.csv
  validation/reinsurance3/expected/ri_info.csv
  validation/reinsurance3/expected/ri_layers.json
  validation/reinsurance3/expected/ri_scope.csv
  validation/reinsurance3/expected/rils.csv
  validation/reinsurance3/location.csv
  validation/reinsurance3/ri_info.csv
  validation/reinsurance3/ri_scope.csv
  validation/reinsurance_test_case_list.xlsx
Labels: feature, LTS - 2.3

#1513 fix fm files generation for terms with non 0 default value
  oasislmf/preparation/il_inputs.py
Labels: bug

#1514 manual merge of PR 1509 improve perf of file preparation
  oasislmf/computation/generate/files.py
  oasislmf/computation/generate/losses.py
Labels: bug
