Repository OasisLMF/OasisLMF, pull requests merged in 2024-03, with the labels that each got.

#1467 fix for 1 loc with no account fm terms
  oasislmf/preparation/il_inputs.py
  oasislmf/preparation/summaries.py
  oasislmf/utils/defaults.py
Labels: bug, LTS - 1.28, LTS - 2.3

#1458 Enable reinsurance loss output at intermediate inuring priorities
  oasislmf/computation/generate/losses.py
  oasislmf/execution/bash.py
  oasislmf/preparation/summaries.py
  oasislmf/pytools/fm/compute_sparse.py
  oasislmf/pytools/fm/manager.py
  oasislmf/pytools/fmpy.py
Labels: feature, LTS - 2.3

#1472 fix for zero samples
  oasislmf/computation/generate/losses.py
Labels: bug, LTS - 1.27, LTS - 1.28, LTS - 2.3

#1453 Updated OED financial terms supported document
  docs/OED_financial_terms_supported.xlsx
Labels: documentation

#1464 Feature/add fm tests
  validation/insurance_account/account.csv
  validation/insurance_account/expected/coverages.csv
  validation/insurance_account/expected/fm_policytc.csv
  validation/insurance_account/expected/fm_profile.csv
  validation/insurance_account/expected/fm_programme.csv
  validation/insurance_account/expected/fm_summary_map.csv
  validation/insurance_account/expected/fm_xref.csv
  validation/insurance_account/expected/gul_summary_map.csv
  validation/insurance_account/expected/guls.csv
  validation/insurance_account/expected/ils.csv
  validation/insurance_account/expected/items.csv
  validation/insurance_account/expected/keys.csv
  validation/insurance_account/expected/loc_summary.csv
  validation/insurance_account/location.csv
  validation/insurance_account/units/acc101/account.csv
  validation/insurance_account/units/acc101/location.csv
  validation/insurance_account/units/acc102/account.csv
  validation/insurance_account/units/acc102/location.csv
  validation/insurance_account/units/acc103/account.csv
  validation/insurance_account/units/acc103/location.csv
  validation/insurance_account/units/acc104/account.csv
  validation/insurance_account/units/acc104/location.csv
  validation/insurance_account/units/units.txt
  validation/insurance_account_test_case_list.xlsx
  validation/insurance_conditions/account.csv
  validation/insurance_conditions/expected/coverages.csv
  validation/insurance_conditions/expected/fm_policytc.csv
  validation/insurance_conditions/expected/fm_programme.csv
  validation/insurance_conditions/expected/fm_summary_map.csv
  validation/insurance_conditions/expected/fm_xref.csv
  validation/insurance_conditions/expected/gul_summary_map.csv
  validation/insurance_conditions/expected/guls.csv
  validation/insurance_conditions/expected/ils.csv
  validation/insurance_conditions/expected/items.csv
  validation/insurance_conditions/expected/keys.csv
  validation/insurance_conditions/expected/loc_summary.csv
  validation/insurance_conditions/expected_subperils/coverages.csv
  validation/insurance_conditions/expected_subperils/fm_policytc.csv
  validation/insurance_conditions/expected_subperils/fm_programme.csv
  validation/insurance_conditions/expected_subperils/fm_summary_map.csv
  validation/insurance_conditions/expected_subperils/fm_xref.csv
  validation/insurance_conditions/expected_subperils/gul_summary_map.csv
  validation/insurance_conditions/expected_subperils/guls.csv
  validation/insurance_conditions/expected_subperils/ils.csv
  validation/insurance_conditions/expected_subperils/items.csv
  validation/insurance_conditions/expected_subperils/keys.csv
  validation/insurance_conditions/expected_subperils/loc_summary.csv
  validation/insurance_conditions/location.csv
  validation/insurance_conditions/units/sc18/account.csv
  validation/insurance_conditions/units/sc18/location.csv
  validation/insurance_conditions/units/sc19/account.csv
  validation/insurance_conditions/units/sc19/location.csv
  validation/insurance_conditions/units/units.txt
  validation/insurance_conditions_test_case_list.xlsx
Labels: feature, LTS - 2.3

#1474 Use billiard package for keys multiprocess if available
  oasislmf/lookup/factory.py
Labels: bug, LTS - 1.27, LTS - 1.28, LTS - 2.3

#1473 ajust vuln index after vuln_dict has the updated indexes
  oasislmf/pytools/gulmc/items.py
  oasislmf/pytools/gulmc/manager.py
Labels: bug, LTS - 1.28, LTS - 2.3

#1481 Set ktools to 3.12.1
  setup.py
Labels: LTS - 2.3
