Repository OasisLMF/OasisLMF, pull requests merged in 2024-10, with the labels that each got.

#1550 Fix exposure summary report - non covered peril reporting moved
  oasislmf/lookup/builtin.py
  tests/computation/data/common.py
  tests/computation/test_generate_keys.py
  tests/model_preparation/meta_data/keys-errors.csv
Labels: production, LTS - 2.3

#1568 Add check for alt_meanonly output request to conditional
  oasislmf/execution/bin.py
Labels: LTS - 2.3

#1558 support for having several pla sets
  oasislmf/computation/generate/files.py
  oasislmf/computation/generate/losses.py
  oasislmf/execution/bin.py
Labels: LTS - 2.3

#1570 intensity adjustments in dynamic footprint
  oasislmf/computation/generate/losses.py
  oasislmf/execution/bash.py
  oasislmf/execution/runner.py
  oasislmf/lookup/builtin.py
  oasislmf/lookup/factory.py
  oasislmf/preparation/gul_inputs.py
  oasislmf/preparation/summaries.py
  oasislmf/pytools/getmodel/footprint.py
  oasislmf/pytools/gulmc/cli.py
  oasislmf/pytools/gulmc/common.py
  oasislmf/pytools/gulmc/items.py
  oasislmf/pytools/gulmc/manager.py
  oasislmf/utils/defaults.py
  tests/assets/test_adjustments_1/input/gul_summary_map.csv
  tests/assets/test_model_1/input/gul_summary_map.csv
  tests/assets/test_model_2/input/gul_summary_map.csv
  tests/assets/test_model_3/input/gul_summary_map.csv
  tests/assets/test_model_4/input/gul_summary_map.csv
  tests/assets/test_model_5/input/gul_summary_map.csv
  tests/assets/test_model_6/input/gul_summary_map.csv
  tests/assets/test_model_7/input/gul_summary_map.csv
Labels: LTS - 2.3

#1574 Fix missing complex keys return without amplification
  oasislmf/lookup/factory.py
  tests/computation/data/common.py
  tests/computation/data/fake_complex_lookup.py
  tests/computation/test_generate_complex_keys.py
Labels: bug, production, LTS - 2.3

#1578 fix: point to the correct source in error message for vulnerabiity_id…
  oasislmf/pytools/getmodel/manager.py
Labels: bug, LTS - 2.3

#1584 Fix: undo 100% correlation if no correlation setting provided in model settings
  oasislmf/computation/generate/files.py
  oasislmf/preparation/correlations.py
  oasislmf/preparation/gul_inputs.py
  tests/preparation/test_correlations.py
Labels: bug, LTS - 2.3

#1587 Added fix for correlation settings
  oasislmf/computation/generate/files.py
  oasislmf/preparation/correlations.py
  oasislmf/utils/data.py
  tests/computation/data/common.py
  tests/computation/test_generate_files.py
Labels: bug, production, LTS - 2.3
