Repository OasisLMF/OasisLMF, pull requests merged in 2024-11, with the labels that each got.

#1597 Project PR action - incorrectly running on external PRs
  .github/workflows/project-PR.yml
Labels: bug, build system

#1576 1250 support risk attaching ra basis in reinsurance
  oasislmf/computation/generate/files.py
  oasislmf/preparation/reinsurance_layer.py
  oasislmf/utils/data.py
  tests/fm/test_fmpy.py
  validation/reinsurance4/account.csv
  validation/reinsurance4/expected/RI_1/fm_policytc.csv
  validation/reinsurance4/expected/RI_1/fm_profile.csv
  validation/reinsurance4/expected/RI_1/fm_programme.csv
  validation/reinsurance4/expected/RI_1/fm_xref.csv
  validation/reinsurance4/expected/account.csv
  validation/reinsurance4/expected/correlations.csv
  validation/reinsurance4/expected/coverages.csv
  validation/reinsurance4/expected/exposure_info.json
  validation/reinsurance4/expected/exposure_summary_levels.json
  validation/reinsurance4/expected/exposure_summary_report.json
  validation/reinsurance4/expected/fm_policytc.csv
  validation/reinsurance4/expected/fm_profile.csv
  validation/reinsurance4/expected/fm_programme.csv
  validation/reinsurance4/expected/fm_summary_map.csv
  validation/reinsurance4/expected/fm_xref.csv
  validation/reinsurance4/expected/gul_summary_map.csv
  validation/reinsurance4/expected/guls.csv
  validation/reinsurance4/expected/ils.csv
  validation/reinsurance4/expected/items.csv
  validation/reinsurance4/expected/keys.csv
  validation/reinsurance4/expected/location.csv
  validation/reinsurance4/expected/output/raw_guls.csv
  validation/reinsurance4/expected/output/raw_ils.csv
  validation/reinsurance4/expected/output/ri1.csv
  validation/reinsurance4/expected/ri_info.csv
  validation/reinsurance4/expected/ri_layers.json
  validation/reinsurance4/expected/ri_scope.csv
  validation/reinsurance4/expected/rils.csv
  validation/reinsurance4/location.csv
  validation/reinsurance4/ri_info.csv
  validation/reinsurance4/ri_scope.csv
Labels: feature, LTS - 2.3

#1596 Feature/multi perils geo grid
  oasislmf/lookup/builtin.py
  tests/model_preparation/meta_data/keys-geo_grid.csv
  tests/model_preparation/meta_data/location-geo_grid.csv
  tests/model_preparation/meta_data/lookup_config-geo_grid.json
  tests/model_preparation/test_lookup.py
Labels: bug, feature, LTS - 2.3

#1589 Update platform API client for Cyber models
  oasislmf/computation/run/platform.py
  tests/computation/test_platform.py
Labels: enhancement, LTS - 2.3
