Repository OasisLMF/OasisLMF, pull requests merged in 2024-07, with the labels that each got.

#1517 event ranges
  oasislmf/execution/bin.py
Labels: enhancement, LTS - 2.3

#1518 Fix/pre analysis user dir
  oasislmf/computation/hooks/post_analysis.py
  oasislmf/computation/hooks/pre_analysis.py
  tests/computation/test_post_analysis.py
Labels: enhancement, LTS - 1.28, LTS - 2.3

#1524 add post file gen and pre loss calculation step
  oasislmf/cli/model.py
  oasislmf/computation/hooks/post_file_gen.py
  oasislmf/computation/hooks/pre_loss.py
  oasislmf/computation/run/generate_files.py
  oasislmf/computation/run/generate_losses.py
  oasislmf/computation/run/model.py
  oasislmf/manager.py
  tests/computation/test_run_generate_files.py
  tests/computation/test_run_model.py
Labels: feature, LTS - 2.3

#1496 oasis flood push
  oasislmf/_data/action_tree.p
  oasislmf/lookup/builtin.py
  oasislmf/lookup/factory.py
  oasislmf/preparation/gul_inputs.py
  oasislmf/pytools/getmodel/common.py
  oasislmf/pytools/getmodel/footprint.py
  oasislmf/pytools/getmodel/manager.py
  oasislmf/pytools/gulmc/manager.py
  oasislmf/utils/defaults.py
Labels: feature, LTS - 2.3

#1532 make all compute step run command oasis logged
  oasislmf/computation/base.py
  tests/computation/test_generate_losses.py
  tests/computation/test_platform.py
Labels: LTS - 2.3
