Repository OasisLMF/OasisLMF, pull requests merged in 2024-06, with the labels that each got.

#1516 Added support for occurrence attachment for Per Risk XL
  docs/OED_financial_terms_supported.xlsx
  oasislmf/preparation/reinsurance_layer.py
Labels: feature, LTS - 2.3

#1490 Add .json configuration to the sphinx docs generation process
  docs/source/building-and-running-models.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/options_config_file.rst
Labels: documentation, LTS - 2.3

#1521 get_vulns update
  oasislmf/pytools/getmodel/manager.py
  oasislmf/pytools/gulmc/manager.py
Labels: bug, LTS - 2.3
