Repository OasisLMF/OasisLMF, pull requests merged in 2024-02, with the labels that each got.

#1429 franchise deductible
  oasislmf/_data/calc_rules_direct.csv
  oasislmf/pytools/fm/policy.py
  oasislmf/pytools/fm/policy_extras.py
  validation/insurance_and_step/account.csv
  validation/insurance_and_step/expected/coverages.csv
  validation/insurance_and_step/expected/fm_policytc.csv
  validation/insurance_and_step/expected/fm_profile.csv
  validation/insurance_and_step/expected/fm_programme.csv
  validation/insurance_and_step/expected/fm_summary_map.csv
  validation/insurance_and_step/expected/fm_xref.csv
  validation/insurance_and_step/expected/gul_summary_map.csv
  validation/insurance_and_step/expected/guls.csv
  validation/insurance_and_step/expected/ils.csv
  validation/insurance_and_step/expected/items.csv
  validation/insurance_and_step/expected/keys.csv
  validation/insurance_and_step/expected/loc_summary.csv
  validation/insurance_and_step/expected_subperils/coverages.csv
  validation/insurance_and_step/expected_subperils/fm_policytc.csv
  validation/insurance_and_step/expected_subperils/fm_profile.csv
  validation/insurance_and_step/expected_subperils/fm_programme.csv
  validation/insurance_and_step/expected_subperils/fm_summary_map.csv
  validation/insurance_and_step/expected_subperils/fm_xref.csv
  validation/insurance_and_step/expected_subperils/gul_summary_map.csv
  validation/insurance_and_step/expected_subperils/guls.csv
  validation/insurance_and_step/expected_subperils/ils.csv
  validation/insurance_and_step/expected_subperils/items.csv
  validation/insurance_and_step/expected_subperils/keys.csv
  validation/insurance_and_step/expected_subperils/loc_summary.csv
  validation/insurance_and_step/location.csv
  validation/insurance_and_step/units/fmFranchise/account.csv
  validation/insurance_and_step/units/fmFranchise/location.csv
  validation/insurance_and_step/units/units.txt
Labels: enhancement

#1415 Replace single vulnerabilities through additional adjustments settings or file
  oasislmf/computation/generate/files.py
  oasislmf/pytools/getmodel/manager.py
  oasislmf/pytools/gulmc/manager.py
  oasislmf/utils/data.py
  tests/pytools/test_getmodel/test_get_model.py
  tests/utils/test_data.py
Labels: enhancement

#1441 Feature/lot3 merge
  .github/workflows/piwind-test.yml
  .github/workflows/publish.yml
  model-storage.md
  oasislmf/computation/generate/files.py
  oasislmf/computation/generate/losses.py
  oasislmf/computation/hooks/pre_analysis.py
  oasislmf/computation/run/generate_files.py
  oasislmf/execution/bash.py
  oasislmf/execution/bin.py
  oasislmf/execution/runner.py
  oasislmf/lookup/builtin.py
  oasislmf/pytools/data_layer/conversions/footprint.py
  oasislmf/pytools/data_layer/footprint_layer.py
  oasislmf/pytools/data_layer/oasis_files/correlations.py
  oasislmf/pytools/fm/policy.py
  oasislmf/pytools/fm/policy_extras.py
  oasislmf/pytools/getmodel/footprint.py
  oasislmf/pytools/getmodel/manager.py
  oasislmf/pytools/getmodel/vulnerability.py
  oasislmf/pytools/gul/manager.py
  oasislmf/pytools/gulmc/aggregate.py
  oasislmf/pytools/gulmc/cli.py
  oasislmf/pytools/gulmc/manager.py
  oasislmf/pytools/modelpy.py
  oasislmf/pytools/pla/manager.py
  oasislmf/pytools/pla/structure.py
  oasislmf/utils/exceptions.py
  requirements-package.in
  scripts/run_model.py
  setup.py
  tests/computation/data/ord_bash_script.sh
  tests/model_execution/test_bin.py
  tests/model_preparation/test_reinsurance.py
  tests/pytools/fm/test_policy.py
  tests/pytools/fm/test_policy_extra.py
  tests/pytools/test_getmodel/static/vulnerability_dataset/part_0.parquet
  tests/pytools/test_getmodel/test_get_model.py
  tests/pytools/test_getmodel/vulnerability_dataset/part_0.parquet
  tests/utils/test_data.py
  tests/utils/test_log.py
Labels: feature

#1446 Add missing loc_id check
  .github/workflows/piwind-test.yml
  oasislmf/computation/generate/files.py
  tests/computation/data/common.py
  tests/computation/test_generate_files.py
Labels: LTS - 1.26, LTS - 1.27, LTS - 1.28

#1448 ensure header is written in keys.csv
  oasislmf/lookup/factory.py
Labels: bug

#1444 support for pandas 3
  oasislmf/lookup/builtin.py
Labels: bug, LTS - 2.3

#1457 Update OasisAPI client to poll analysis status using `run_mode`
  oasislmf/platform_api/client.py
  tests/platform_api/test_client.py
Labels: bug, LTS - 2.3

#1459 Fixed package requirments
  optional-package.in
  requirements-package.in
Labels: dependencies, LTS - 1.28, LTS - 2.3

#1447 use correct error_model in back allocation
  oasislmf/pytools/fm/back_allocation.py
  oasislmf/pytools/fm/compute_sparse.py
  oasislmf/pytools/fm/manager.py
Labels: bug, production, LTS - 1.27, LTS - 1.28, LTS - 2.3

#1450 Fix parquet checks
  oasislmf/execution/bin.py
  tests/model_execution/test_bin.py
Labels: bug, LTS - 2.3

#1455 fix for vuln parquet read
  oasislmf/pytools/getmodel/manager.py
Labels: bug, LTS - 2.3

#1463 Fix missing occurrence file when aalcalcmeanonly output requested
  oasislmf/execution/bin.py
Labels: bug, LTS - 1.28, LTS - 2.3

#1456 Allow optional hazard or damage correlation value
  oasislmf/computation/generate/files.py
  oasislmf/preparation/correlations.py
  tests/preparation/test_correlations.py
Labels: bug, LTS - 1.27, LTS - 1.28, LTS - 2.3
