Repository OasisLMF/OasisLMF, pull requests merged in 2025-03, with the labels that each got.

#1653 fix for empty geopandas df sjoin not supported in geopandas 1.x
  oasislmf/lookup/builtin.py
Labels: bug, LTS - 1.28, LTS - 2.3, LTS - 2.4

#1654 Improve loading and memory usage of Aggregate Vulnerability
  oasislmf/pytools/gulmc/aggregate.py
  oasislmf/pytools/gulmc/manager.py
Labels: bug, enhancement, LTS - 1.28, LTS - 2.3, LTS - 2.4

#1649 Non-NumBa Error Logging
  oasislmf/computation/generate/losses.py
  oasislmf/execution/bash.py
  oasislmf/execution/runner.py
  oasislmf/pytools/common/event_stream.py
  oasislmf/pytools/data_layer/footprint_layer.py
  oasislmf/pytools/fm/compare.py
  oasislmf/pytools/fm/manager.py
  oasislmf/pytools/gulmc/manager.py
  oasislmf/pytools/summary/manager.py
  oasislmf/utils/exceptions.py
Labels: enhancement, LTS - 2.4

#1648 in fm add polnumber information to level with no terms
  oasislmf/preparation/il_inputs.py
  validation/insurance/expected/fm_policytc.csv
  validation/insurance/expected/fm_profile.csv
  validation/insurance/expected/fm_programme.csv
  validation/insurance/expected_subperils/fm_policytc.csv
  validation/insurance/expected_subperils/fm_profile.csv
  validation/insurance/expected_subperils/fm_programme.csv
  validation/insurance_account/expected/fm_policytc.csv
  validation/insurance_account/expected/fm_profile.csv
  validation/insurance_account/expected/fm_programme.csv
  validation/insurance_and_step/expected/fm_policytc.csv
  validation/insurance_and_step/expected/fm_programme.csv
  validation/insurance_and_step/expected/fm_summary_map.csv
  validation/insurance_and_step/expected_subperils/fm_policytc.csv
  validation/insurance_and_step/expected_subperils/fm_programme.csv
  validation/insurance_and_step/expected_subperils/fm_summary_map.csv
  validation/insurance_conditions/expected/fm_policytc.csv
  validation/insurance_conditions/expected/fm_profile.csv
  validation/insurance_conditions/expected/fm_programme.csv
  validation/insurance_conditions/expected_subperils/fm_policytc.csv
  validation/insurance_conditions/expected_subperils/fm_profile.csv
  validation/insurance_conditions/expected_subperils/fm_programme.csv
  validation/insurance_policy_coverage/expected/fm_policytc.csv
  validation/insurance_policy_coverage/expected/fm_profile.csv
  validation/insurance_policy_coverage/expected_subperils/fm_policytc.csv
  validation/insurance_policy_coverage/expected_subperils/fm_profile.csv
  validation/issues/expected/fm_policytc.csv
  validation/issues/expected/fm_profile.csv
  validation/issues/expected/fm_programme.csv
  validation/issues/expected_subperils/fm_policytc.csv
  validation/issues/expected_subperils/fm_profile.csv
  validation/issues/expected_subperils/fm_programme.csv
  validation/reinsurance1/expected/fm_policytc.csv
  validation/reinsurance1/expected/fm_profile.csv
  validation/reinsurance1/expected/fm_programme.csv
  validation/reinsurance1/expected_subperils/fm_policytc.csv
  validation/reinsurance1/expected_subperils/fm_profile.csv
  validation/reinsurance1/expected_subperils/fm_programme.csv
  validation/reinsurance2/expected/fm_policytc.csv
  validation/reinsurance2/expected/fm_profile.csv
  validation/reinsurance2/expected/fm_programme.csv
  validation/reinsurance2/expected_subperils/fm_policytc.csv
  validation/reinsurance2/expected_subperils/fm_profile.csv
  validation/reinsurance2/expected_subperils/fm_programme.csv
Labels: bug, LTS - 1.28, LTS - 2.3, LTS - 2.4

#1665 add support for geotiff in buildin lookup
  oasislmf/lookup/builtin.py
Labels: feature, LTS - 2.4
