Repository OasisLMF/OasisLMF, pull requests merged in 2025-08, with the labels that each got.

#1740 support for mac M2 multiprocessing lookup
  oasislmf/lookup/factory.py
Labels: bug

#1757 add settings template endpoint to api client
  oasislmf/platform_api/client.py
  tests/platform_api/test_client.py
Labels: enhancement

#1745 feature/BI improvement FM
  oasislmf/_data/calc_rules_direct.csv
  oasislmf/_data/default_acc_profile.json
  oasislmf/_data/default_combined_exposure_profile.json
  oasislmf/_data/default_fm_agg_profile.json
  oasislmf/_data/default_loc_profile.json
  oasislmf/preparation/il_inputs.py
  oasislmf/pytools/fm/compute_sparse.py
  oasislmf/pytools/fm/policy.py
  oasislmf/pytools/fm/policy_extras.py
  oasislmf/pytools/gulmc/manager.py
  oasislmf/utils/data.py
  oasislmf/utils/defaults.py
  oasislmf/utils/fm.py
  oasislmf/utils/profiles.py
  tests/fm/test_fmpy.py
  validation/insurance_bi/account.csv
  validation/insurance_bi/expected/coverages.csv
  validation/insurance_bi/expected/fm_policytc.csv
  validation/insurance_bi/expected/fm_profile.csv
  validation/insurance_bi/expected/fm_programme.csv
  validation/insurance_bi/expected/fm_summary_map.csv
  validation/insurance_bi/expected/fm_xref.csv
  validation/insurance_bi/expected/gul_summary_map.csv
  validation/insurance_bi/expected/guls.csv
  validation/insurance_bi/expected/ils.csv
  validation/insurance_bi/expected/items.csv
  validation/insurance_bi/expected/keys.csv
  validation/insurance_bi/expected/loc_summary.csv
  validation/insurance_bi/expected_subperils/coverages.csv
  validation/insurance_bi/expected_subperils/fm_policytc.csv
  validation/insurance_bi/expected_subperils/fm_profile.csv
  validation/insurance_bi/expected_subperils/fm_programme.csv
  validation/insurance_bi/expected_subperils/fm_summary_map.csv
  validation/insurance_bi/expected_subperils/fm_xref.csv
  validation/insurance_bi/expected_subperils/gul_summary_map.csv
  validation/insurance_bi/expected_subperils/guls.csv
  validation/insurance_bi/expected_subperils/ils.csv
  validation/insurance_bi/expected_subperils/items.csv
  validation/insurance_bi/expected_subperils/keys.csv
  validation/insurance_bi/expected_subperils/loc_summary.csv
  validation/insurance_bi/location.csv
  validation/insurance_bi/loss_factors.csv
  validation/insurance_bi/units/BI_1/account.csv
  validation/insurance_bi/units/BI_1/location.csv
  validation/insurance_bi/units/BI_2/account.csv
  validation/insurance_bi/units/BI_2/location.csv
  validation/insurance_bi/units/units.txt
Labels: feature
