Repository OasisLMF/OasisLMF, pull requests merged in 2025-01, with the labels that each got.

#1618 Fix testing failures (API Client)
  .github/workflows/build-docs.yml
  requirements.in
Labels: bug, build system, LTS - 2.3, LTS - 2.4

#1611 fix loss_out len in account level back allocation
  oasislmf/pytools/fm/compute_sparse.py
Labels: bug, LTS - 1.28, LTS - 2.3, LTS - 2.4

#1614 fixes error message for missing PolInceptionDate
  oasislmf/preparation/reinsurance_layer.py
Labels: LTS - 2.3, LTS - 2.4

#1552 Make analysis and model setting able to modify any computation step parameters (MDK parameters)
  oasislmf/cli/command.py
  oasislmf/cli/model.py
  oasislmf/computation/base.py
  oasislmf/computation/generate/files.py
  oasislmf/computation/generate/keys.py
  oasislmf/computation/generate/losses.py
  oasislmf/computation/run/model.py
  oasislmf/manager.py
  oasislmf/pytools/getmodel/manager.py
  oasislmf/utils/data.py
  oasislmf/utils/inputs.py
  tests/computation/data/common.py
  tests/computation/data/fake_model_settings.json
  tests/computation/test_computation.py
  tests/computation/test_generate_complex_keys.py
  tests/computation/test_generate_keys.py
  tests/computation/test_generate_losses.py
  tests/computation/test_platform.py
  tests/computation/test_run_generate_files.py
  tests/computation/test_run_model.py
  tests/model_preparation/meta_data/analysis_settings.json
  tests/model_preparation/meta_data/model_settings.json
  tests/pytools/test_getmodel/test_get_model.py
  tests/utils/test_data.py
Labels: feature, LTS - 2.4
