Repository OasisLMF/OasisLMF, pull requests merged in 2025-04, with the labels that each got.

#1673 add calculated summary column for PD
  oasislmf/computation/run/exposure.py
  oasislmf/preparation/summaries.py
Labels: feature

#1672 eltpy sum loss and sum loss square need to be float64 to avoid to much precision error
  oasislmf/pytools/elt/manager.py
  tests/assets/test_eltpy/py_melt.csv
  tests/assets/test_eltpy/py_melt_er.csv
Labels: enhancement, Impact Loss Result

#1685 Fixed health check exception on api connect
  oasislmf/computation/run/platform.py
Labels: bug, LTS - 1.28, LTS - 2.3, LTS - 2.4
