Repository OasisLMF/OasisLMF, pull requests merged in 2025-02, with the labels that each got.

#1628 Update pages workflow
  .github/workflows/build-and-deploy-docs.yml
Labels: bug, build system

#1630 fix issue with loc id
  oasislmf/computation/hooks/pre_analysis.py
  oasislmf/preparation/summaries.py
Labels: bug, LTS - 2.4

#1631 specify parquet folder to improve footprint read time
  oasislmf/pytools/getmodel/footprint.py
Labels: enhancement, LTS - 2.4

#1633 fix missing cond column when no term present
  oasislmf/preparation/il_inputs.py
Labels: bug, LTS - 1.28, LTS - 2.3, LTS - 2.4

#1634 Update release section in readme
  README.md
Labels: documentation

#1635 Refactor/preparation oed
  oasislmf/preparation/oed.py
  oasislmf/preparation/reinsurance_layer.py
  oasislmf/utils/oed.py
  tests/model_preparation/test_oed.py
Labels: LTS - 2.4

#1638 CI Fix, Skip incompatible client checks
  tests/platform_api/test_client.py
Labels: bug, build system, LTS - 2.4
